// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { echo, hello, type Options, up } from '../sdk.gen';
import type { EchoData, EchoError, EchoResponse, HelloData, HelloResponse, UpData, UpError, UpResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const helloQueryKey = (options?: Options<HelloData>) => createQueryKey('hello', options);

/**
 * Hello
 */
export const helloOptions = (options?: Options<HelloData>) => queryOptions<HelloResponse, DefaultError, HelloResponse, ReturnType<typeof helloQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await hello({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: helloQueryKey(options)
});

export const echoQueryKey = (options: Options<EchoData>) => createQueryKey('echo', options);

/**
 * Echo
 */
export const echoOptions = (options: Options<EchoData>) => queryOptions<EchoResponse, EchoError, EchoResponse, ReturnType<typeof echoQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await echo({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: echoQueryKey(options)
});

export const upQueryKey = (options: Options<UpData>) => createQueryKey('up', options);

/**
 * Echo
 */
export const upOptions = (options: Options<UpData>) => queryOptions<UpResponse, UpError, UpResponse, ReturnType<typeof upQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await up({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: upQueryKey(options)
});
