// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { hello, type Options, repeat } from '../sdk.gen';
import type { HelloData, HelloResponse, RepeatData, RepeatError, RepeatResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const helloQueryKey = (options?: Options<HelloData>) => createQueryKey('hello', options);

/**
 * Hello
 */
export const helloOptions = (options?: Options<HelloData>) => queryOptions<HelloResponse, DefaultError, HelloResponse, ReturnType<typeof helloQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await hello({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: helloQueryKey(options)
});

export const repeatQueryKey = (options: Options<RepeatData>) => createQueryKey('repeat', options);

/**
 * Echo
 */
export const repeatOptions = (options: Options<RepeatData>) => queryOptions<RepeatResponse, RepeatError, RepeatResponse, ReturnType<typeof repeatQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await repeat({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: repeatQueryKey(options)
});
