// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { EchoData, EchoErrors, EchoResponses, HelloData, HelloResponses, UpData, UpErrors, UpResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Hello
 */
export const hello = <ThrowOnError extends boolean = false>(options?: Options<HelloData, ThrowOnError>): RequestResult<HelloResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HelloResponses, unknown, ThrowOnError>({ url: '/hello', ...options });

/**
 * Echo
 */
export const echo = <ThrowOnError extends boolean = false>(options: Options<EchoData, ThrowOnError>): RequestResult<EchoResponses, EchoErrors, ThrowOnError> => (options.client ?? client).get<EchoResponses, EchoErrors, ThrowOnError>({ url: '/echo/{text}', ...options });

/**
 * Echo
 */
export const up = <ThrowOnError extends boolean = false>(options: Options<UpData, ThrowOnError>): RequestResult<UpResponses, UpErrors, ThrowOnError> => (options.client ?? client).get<UpResponses, UpErrors, ThrowOnError>({ url: '/upupup/{text}', ...options });
