// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Item
 */
export type Item = {
    /**
     * Message
     */
    message: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/hello';
};

export type HelloResponses = {
    /**
     * Successful Response
     */
    200: Item;
};

export type HelloResponse = HelloResponses[keyof HelloResponses];

export type EchoData = {
    body?: never;
    path: {
        /**
         * Text
         */
        text: string;
    };
    query?: never;
    url: '/echo/{text}';
};

export type EchoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EchoError = EchoErrors[keyof EchoErrors];

export type EchoResponses = {
    /**
     * Successful Response
     */
    200: Item;
};

export type EchoResponse = EchoResponses[keyof EchoResponses];

export type UpData = {
    body?: never;
    path: {
        /**
         * Text
         */
        text: string;
    };
    query?: never;
    url: '/upupup/{text}';
};

export type UpErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpError = UpErrors[keyof UpErrors];

export type UpResponses = {
    /**
     * Successful Response
     */
    200: Item;
};

export type UpResponse = UpResponses[keyof UpResponses];
