// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * ErrorDetails
 */
export type ErrorDetails = {
    /**
     * Details
     */
    details: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Item
 */
export type Item = {
    /**
     * Message
     */
    message: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/hello';
};

export type HelloResponses = {
    /**
     * Successful Response
     */
    200: Item;
};

export type HelloResponse = HelloResponses[keyof HelloResponses];

export type RepeatData = {
    body?: never;
    path: {
        /**
         * Count
         */
        count: number;
    };
    query: {
        /**
         * Text
         */
        text: string;
    };
    url: '/repeat/{count}';
};

export type RepeatErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetails;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RepeatError = RepeatErrors[keyof RepeatErrors];

export type RepeatResponses = {
    /**
     * Successful Response
     */
    200: Item;
};

export type RepeatResponse = RepeatResponses[keyof RepeatResponses];
